### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by sakuolinold** [BlitzConfusion/CivIVCombatCalculator#1]

**Comment by BlitzConfusion** [comment]
sakuolin kirjoitti 2016-02-02 15:53:
> Zip -kansio ladattu ja koodi "katselmoitu" 222016 @ 15:38 Graafista
> käyttöliittymää tai Main -metodia ei vielä ollut olemassa, joten
> annan palautetta vain luokkien luettavuudesta
> 
> Ensinnäkin, luokat olivat kaikki lyhyitä ja ytimekkäitä, ja niiden
> käyttötarkoituksen sai selville itse luokan nimestä ja niiden
> metodeista Koodi oli jaettu hyvin per metodi, ei liian pitkiä
> koodinpalasia häiritsemässä ja vaikeuttamassa lukemista
> 
> Yhtenä huomautuksena voisin mainita pakettien käytöstä, sillä
> tällä hetkellä kaikki luokat ovat samassa paikassa Vai onko
> tarkoituksellista?
> 
> --
Hei.

Tässä alustavassa vaiheessa oli täysin tarkoituksellista että kaikki 
loytyy samasta paikasta.
Graafinen käyttöliittymä tulee omaan pakettiinsa lopullisessa versiossa, 
samoin kuin mahdollisesti voimasuhteen laskija.

Toisesta aiheesta: Nyt on niin, että olen ollut viikon alusta asti 
nuhakuumeessa, ja jos se ei olisi ollut tarpeeksi kivaa jo, sain nyt 
migreenikohtauksen pitämään seuraa kuumeelleni.
Eli katson tarpeelliseksi todeta etten kykene suoriutumaan kaikista 
tehtävistäni nykuisessä toimintakunnossa ja pyytäisin siis Deadlineni 
siirtoa seuraavan palautukseni osalta ensi viikon maanantaille vaikka 
23:59.

Terv. Linna, Lauri Johannes

**Comment by BlitzConfusion** [comment]
sakuolin kirjoitti 2016-02-02 15:53:

> Zip -kansio ladattu ja koodi "katselmoitu" 222016 @ 15:38 Graafista
> käyttöliittymää tai Main -metodia ei vielä ollut olemassa, joten
> annan palautetta vain luokkien luettavuudesta
> 
> Ensinnäkin, luokat olivat kaikki lyhyitä ja ytimekkäitä, ja niiden
> käyttötarkoituksen sai selville itse luokan nimestä ja niiden
> metodeista Koodi oli jaettu hyvin per metodi, ei liian pitkiä
> koodinpalasia häiritsemässä ja vaikeuttamassa lukemista
> 
> Yhtenä huomautuksena voisin mainita pakettien käytöstä, sillä
> tällä hetkellä kaikki luokat ovat samassa paikassa Vai onko
> tarkoituksellista?
> 
> ## 
> 
> Koodin tässä vaiheessa tämä oli tarkoituksellista. Graafinen 
> käyttöliittymä tulee omaan pakettiinsa myöhemmin, samoin kuin 
> mahdollisesti erikseen nykyinen comparator.

Jos sait viestin tätä ennen, jätä se huomiotta. Kuumeessani menin 
sekaisin tekemistäni viesteistä, enkä huomannut sitä ennen kuin nyt.

**Comment by sakuolin** [comment]
This issue was left open for, so I closed it. Could also just delete it at this point.

**Comment by sakuolin** [comment]
This issue was left open, so I closed it. Could just be deleted at this point.
